/** @format */

import Head from "next/head";
import Image from "next/image";

import styled from "styled-components";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Gmail Clone App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<h1>Gmail Clone </h1>
			</main>

			<footer>
				<DivTest>ok</DivTest>
			</footer>
		</div>
	);
}

const DivTest = styled.div``;
